/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6K7KOIP6juI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import Image from 'next/image'

export function LandingPage() {
  return (
    (<div className="flex flex-col items-center w-full min-h-screen bg-[#f5f5f5]">
      <header className="w-full bg-[#f0ebe3] text-[#333] py-4">
        <nav className="container flex items-center justify-between mx-auto">
          <h1 className="text-2xl font-bold">Vijayalaxmi Furnishings</h1>
          <ul className="flex space-x-4">
            <li>
              <a href="#" className="hover:underline">
                Home
              </a>
            </li>
            <li>
              <a href="#" className="hover:underline">
                Products
              </a>
            </li>
            <li>
              <a href="#" className="hover:underline">
                About Us
              </a>
            </li>
            <li>
              <a href="#" className="hover:underline">
                Contact
              </a>
            </li>
          </ul>
          <div className="flex items-center space-x-4">
            <a href="#" className="hover:underline">
              Login
            </a>
            <a href="#" className="bg-[#f0ebe3] text-[#333] px-4 py-2 rounded">
              Sign Up
            </a>
          </div>
        </nav>
      </header>
      <main className="container mx-auto mt-8 space-y-16">
        <section className="flex flex-col items-center text-center space-y-4">
          <h2 className="text-4xl font-bold">Make your home more beautiful than ever</h2>
          <p className="text-lg text-[#666]">
            High Quality Material | 5 Year Service Guarantee | Designed by World Class Designers
          </p>
          <Button className="bg-[#f0ebe3] text-[#333] px-6 py-3">Explore Now</Button>
        </section>
        <section className="text-center">
          <h3 className="text-3xl font-bold mb-8">Signature Items</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <Card className="flex flex-col items-center space-y-4">
              <Image
                src="https://www.ikea.com/in/en/images/products/oestanoe-chair-deep-green-remmarn-deep-green__1209972_pe909498_s5.jpg?f=xl"
                alt="Chair"
                className="w-48 h-48 object-cover"
                width="200"
                height="200"
                style={{ aspectRatio: "200/200", objectFit: "cover" }} />
              <h4 className="text-xl font-semibold">Stylish Chair</h4>
              <Button className="bg-[#f0ebe3] text-[#333] px-4 py-2">Explore Now</Button>
            </Card>
            <Card className="flex flex-col items-center space-y-4">
              <Image
                src="https://www.ikea.com/in/en/images/products/gammalbyn-3-seat-sofa-blue__0868912_pe781422_s5.jpg?f=xl"
                alt="Sofa"
                className="w-48 h-48 object-cover"
                width="200"
                height="200"
                style={{ aspectRatio: "200/200", objectFit: "cover" }} />
              <h4 className="text-xl font-semibold">Comfortable Sofa</h4>
              <Button className="bg-[#f0ebe3] text-[#333] px-4 py-2">Explore Now</Button>
            </Card>
            <Card className="flex flex-col items-center space-y-4">
              <img
                src="https://www.ikea.com/in/en/images/products/linnmon-adils-table-white__0737165_pe740925_s5.jpg?f=xl"
                alt="Table"
                className="w-48 h-48 object-cover"
                width="200"
                height="200"
                style={{ aspectRatio: "200/200", objectFit: "cover" }} />
              <h4 className="text-xl font-semibold">Elegant Table</h4>
              <Button className="bg-[#f0ebe3] text-[#333] px-4 py-2">Explore Now</Button>
            </Card>
            <Card className="flex flex-col items-center space-y-4">
              <Image
                src="https://www.ikea.com/in/en/images/products/barlast-floor-lamp-black-white__0957677_pe805131_s5.jpg?f=xl"
                alt="Lamp"
                className="w-48 h-48 object-cover"
                width="200"
                height="200"
                style={{ aspectRatio: "200/200", objectFit: "cover" }} />
              <h4 className="text-xl font-semibold">Modern Lamp</h4>
              <Button className="bg-[#f0ebe3] text-[#333] px-4 py-2">Explore Now</Button>
            </Card>
          </div>
        </section>
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h3 className="text-3xl font-bold">Feedback from our real customers</h3>
            <p className="text-lg text-[#666]">
              "The quality of the furniture is outstanding. I am very satisfied with my purchase!" - Jane Doe
            </p>
          </div>
          <div className="space-y-4">
            <h3 className="text-3xl font-bold">Frequently Asked Questions</h3>
            <ul className="space-y-2">
              <li className="text-lg text-[#666]">What is the return policy?</li>
              <li className="text-lg text-[#666]">How long is the warranty?</li>
              <li className="text-lg text-[#666]">Do you offer free shipping?</li>
              <li className="text-lg text-[#666]">Can I customize my order?</li>
            </ul>
          </div>
        </section>
        <section className="text-center space-y-4">
          <h3 className="text-3xl font-bold">Have any query? Contact us now!</h3>
          <form className="flex flex-col items-center space-y-4">
            <Input
              type="email"
              placeholder="Your Email"
              className="w-64 px-4 py-2 border rounded" />
            <Button className="bg-[#f0ebe3] text-[#333] px-6 py-3">Send Message</Button>
          </form>
        </section>
      </main>
      <footer className="w-full bg-[#f0ebe3] text-[#333] py-4 mt-16">
        <div className="container mx-auto text-center">
          <p>&copy; 2023 FurniCo. All rights reserved.</p>
        </div>
      </footer>
    </div>)
  );
}
